import 'package:flutter/material.dart';

class EventProvider with ChangeNotifier {
  int currentIndex = 0;

  

  final List<Map<String, String>> ongoingEvents = [
  {
    'title': 'Giảm 50% cho mọi đơn',
    'image': 'assets/images/bg1.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Highlands Coffee',
    'detail': 'Ưu đãi giảm 50% cho mọi đơn hàng khi sử dụng ứng dụng.',
    'voucherCount': '100',
    'voucherUsed': '50',
    'startDate': '01/12/2024',
    'endDate': '31/12/2024',
  },
  {
    'title': 'Ưu đãi đặc biệt cuối tuần',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'TocoToco',
    'detail': 'Giảm giá đặc biệt vào cuối tuần khi mua từ 2 sản phẩm trở lên.',
    'voucherCount': '50',
    'voucherUsed': '20',
    'startDate': '06/12/2024',
    'endDate': '16/12/2024',
  },
  {
    'title': 'Tặng 1 nước khi mua 2 ly',
    'image': 'assets/images/bg2.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Fashion',
    'detail': 'Mua 2 ly bất kỳ tặng thêm 1 ly miễn phí chỉ trong tuần này.',
    'voucherCount': '200',
    'voucherUsed': '50',
    'startDate': '01/12/2024',
    'endDate': '20/12/2024',
  },
  {
    'title': 'Ưu đãi giờ vàng',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'KATINAT',
    'detail': 'Giảm 30% cho tất cả đơn hàng trong khung giờ vàng 16:00 - 18:00.',
    'voucherCount': '300',
    'voucherUsed': '110',
    'startDate': '10/12/2024',
    'endDate': '10/01/2025',
  },
  {
    'title': 'Khuyến mãi 1 tặng 1',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'WARRIOR',
    'detail': 'Mua 1 tặng 1 khi sử dụng voucher tại cửa hàng WARRIOR.',
    'voucherCount': '150',
    'voucherUsed': '50',
    'startDate': '15/12/2024',
    'endDate': '15/01/2025',
  },
  {
    'title': 'Đồng giá 20K',
    'image': 'assets/images/bg5.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Trà Sữa Đô Đô',
    'detail': 'Mọi sản phẩm đồng giá 20K khi thanh toán bằng ví điện tử.',
    'voucherCount': '250',
    'voucherUsed': '150',
    'startDate': '01/01/2025',
    'endDate': '31/01/2025',
  },
];

final List<Map<String, String>> upcomingEvents = [
  {
    'title': 'Giảm 10% trên mọi hóa đơn',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Highlands Coffee',
    'detail': 'Ưu đãi giảm giá 10% cho mọi hóa đơn trên toàn quốc.',
    'voucherCount': '80',
    'voucherUsed': '50',
    'startDate': '05/01/2025',
    'endDate': '20/01/2025',
  },
  {
    'title': 'Quà tặng sinh nhật',
    'image': 'assets/images/bg1.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'TocoToco',
    'detail': 'Nhận quà tặng miễn phí nhân dịp sinh nhật của bạn.',
    'voucherCount': '100',
    'voucherUsed': '50',
    'startDate': '10/01/2025',
    'endDate': '30/01/2025',
  },
  {
    'title': 'Miễn phí giao hàng',
    'image': 'assets/images/bg2.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Fashion',
    'detail': 'Miễn phí giao hàng cho các đơn hàng từ 150K trở lên.',
    'voucherCount': '200',
    'voucherUsed': '50',
    'startDate': '01/12/2024',
    'endDate': '31/12/2024',
  },
  {
    'title': 'Giảm giá cuối tháng',
    'image': 'assets/images/bg5.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'KATINAT',
    'detail': 'Giảm giá 25% cho tất cả sản phẩm trong dịp cuối tháng.',
    'voucherCount': '300',
    'voucherUsed': '220',
    'startDate': '15/12/2024',
    'endDate': '15/01/2025',
  },
  {
    'title': 'Ưu đãi khách hàng mới',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'WARRIOR',
    'detail': 'Ưu đãi đặc biệt dành cho khách hàng lần đầu mua sắm.',
    'voucherCount': '120',
    'voucherUsed': '90',
    'startDate': '01/01/2025',
    'endDate': '31/01/2025',
  },
  {
    'title': 'Tặng thêm topping miễn phí',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Trà Sữa Đô Đô',
    'detail': 'Thêm topping miễn phí cho tất cả đơn hàng từ 50K.',
    'voucherCount': '150',
    'voucherUsed': '50',
    'startDate': '05/12/2024',
    'endDate': '25/12/2024',
  },
];

final List<Map<String, String>> outstandingEvent = [
  {
    'title': 'Ngày hội giảm giá',
    'image': 'assets/images/bg1.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Highlands Coffee',
    'detail': 'Ngày hội giảm giá cực lớn, lên đến 70% trên toàn quốc.',
    'voucherCount': '500',
    'voucherUsed': '440',
    'startDate': '10/12/2024',
    'endDate': '10/01/2025',
  },
  {
    'title': 'Tặng voucher 50K',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'TocoToco',
    'detail': 'Nhận ngay voucher 50K khi mua hàng trực tuyến.',
    'voucherCount': '300',
    'voucherUsed': '210',
    'startDate': '20/12/2024',
    'endDate': '20/01/2025',
  },
  {
    'title': 'Ưu đãi hội viên VIP',
    'image': 'assets/images/bg2.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Fashion',
    'detail': 'Dành riêng cho khách hàng VIP với ưu đãi hấp dẫn.',
    'voucherCount': '400',
    'voucherUsed': '230',
    'startDate': '01/12/2024',
    'endDate': '12/12/2024',
  },
  {
    'title': 'Khuyến mãi lễ hội mùa xuân',
    'image': 'assets/images/bg5.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'KATINAT',
    'detail': 'Giảm 40% cho toàn bộ sản phẩm dịp lễ hội mùa xuân.',
    'voucherCount': '400',
    'voucherUsed': '350',
    'startDate': '01/12/2024',
    'endDate': '13/12/2024',
  },
  {
    'title': 'Tích điểm đổi quà',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'WARRIOR',
    'detail': 'Tích điểm ngay hôm nay để nhận quà tặng hấp dẫn.',
    'voucherCount': '400',
    'voucherUsed': '330',
    'startDate': '01/12/2024',
    'endDate': '22/12/2024',
  },
  {
    'title': 'Ưu đãi độc quyền',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Trà Sữa Đô Đô',
    'detail': 'Ưu đãi độc quyền chỉ có tại cửa hàng Đô Đô.',
    'voucherCount': '400',
    'voucherUsed': '230',
    'startDate': '01/12/2024',
    'endDate': '25/12/2024',
  },
];

final List<Map<String, String>> endEvent = [
  {
    'title': 'Giảm giá cuối tuần',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Highlands Coffee',
    'detail': 'Sự kiện giảm giá cực hot, kết thúc cuối tuần vừa qua.',
    'voucherCount': '150',
    'voucherUsed': '50',
    'startDate': '15/11/2024',
    'endDate': '25/11/2024',
  },
  {
    'title': 'Ưu đãi Black Friday',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'TocoToco',
    'detail': 'Khuyến mãi Black Friday đã kết thúc, hẹn gặp lại năm sau.',
    'voucherCount': '200',
    'voucherUsed': '50',
    'startDate': '20/11/2024',
    'endDate': '30/11/2024',
  },
];

void updateIndex(int newIndex) {
    currentIndex = newIndex;
    notifyListeners();
  }

  List<Map<String, String>> wishlist = [
    {
    'title': 'Tặng voucher 50K',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'TocoToco',
    'detail': 'Nhận ngay voucher 50K khi mua hàng trực tuyến.',
    'voucherCount': '300',
    'voucherUsed': '210',
    'startDate': '20/12/2024',
    'endDate': '20/01/2025',
  },
  {
    'title': 'Ưu đãi hội viên VIP',
    'image': 'assets/images/bg2.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Fashion',
    'detail': 'Dành riêng cho khách hàng VIP với ưu đãi hấp dẫn.',
    'voucherCount': '400',
    'voucherUsed': '230',
    'startDate': '01/12/2024',
    'endDate': '12/12/2024',
  },
  {
    'title': 'Khuyến mãi lễ hội mùa xuân',
    'image': 'assets/images/bg5.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'KATINAT',
    'detail': 'Giảm 40% cho toàn bộ sản phẩm dịp lễ hội mùa xuân.',
    'voucherCount': '400',
    'voucherUsed': '350',
    'startDate': '01/12/2024',
    'endDate': '13/12/2024',
  },
  {
    'title': 'Tặng 1 nước khi mua 2 ly',
    'image': 'assets/images/bg2.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Fashion',
    'detail': 'Mua 2 ly bất kỳ tặng thêm 1 ly miễn phí chỉ trong tuần này.',
    'voucherCount': '200',
    'voucherUsed': '50',
    'startDate': '01/12/2024',
    'endDate': '20/12/2024',
  },
  {
    'title': 'Ưu đãi giờ vàng',
    'image': 'assets/images/bg3.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'KATINAT',
    'detail': 'Giảm 30% cho tất cả đơn hàng trong khung giờ vàng 16:00 - 18:00.',
    'voucherCount': '300',
    'voucherUsed': '110',
    'startDate': '10/12/2024',
    'endDate': '10/01/2025',
  },
  {
    'title': 'Khuyến mãi 1 tặng 1',
    'image': 'assets/images/bg4.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'WARRIOR',
    'detail': 'Mua 1 tặng 1 khi sử dụng voucher tại cửa hàng WARRIOR.',
    'voucherCount': '150',
    'voucherUsed': '50',
    'startDate': '15/12/2024',
    'endDate': '15/01/2025',
  },
  {
    'title': 'Đồng giá 20K',
    'image': 'assets/images/bg5.png',
    'avatar': 'assets/images/bg1.png',
    'store': 'Trà Sữa Đô Đô',
    'detail': 'Mọi sản phẩm đồng giá 20K khi thanh toán bằng ví điện tử.',
    'voucherCount': '250',
    'voucherUsed': '150',
    'startDate': '01/01/2025',
    'endDate': '31/01/2025',
  },
  ];

 



  
}
